<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Modbus.NET.Core</AssemblyName>
        <RootNamespace>Modbus.NET.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="HslCommunication" Version="12.6.3" />
      <PackageReference Include="Opc.UaFx.Client" Version="2.51.2" />
      <PackageReference Include="S7netplus" Version="0.20.0" />
    </ItemGroup>

</Project>
