name: .NET CI

on:
  push:
    branches: [ "main", "fix/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore AnyPLC.NET.sln
    - name: Build
      run: dotnet build AnyPLC.NET.sln --no-restore
    - name: Test
      run: dotnet test AnyPLC.NET.sln --no-build --verbosity normal
